import { Category, Product } from './types';

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: 'cat-jackets',
    name: 'Leather Jackets',
    slug: 'leather-jackets',
    description: 'Masterfully hand-cut full-grain lambskin, steerhide, and Spanish shearling jackets engineered with British tailoring restraint.',
    image: '/images/luxury/prod-jacket-classic-1.webp',
    displayPriority: 100,
    isActive: true,
  },
  {
    id: 'cat-shoes',
    name: 'Shoes',
    slug: 'shoes',
    description: 'Goodyear-welted dress shoes and hand-burnished Chelsea boots crafted in Northamptonshire and Florence. Matching pairs shown.',
    image: '/images/luxury/prod-shoe-oxford-pair.webp',
    displayPriority: 90,
    isActive: true,
  },
  {
    id: 'cat-bags',
    name: 'Bags',
    slug: 'bags',
    description: 'Structured full-grain leather weekender duffels, briefcases, and architectural travel accessories.',
    image: '/images/luxury/prod-weekender-1.webp',
    displayPriority: 80,
    isActive: true,
  },
  {
    id: 'cat-wallets',
    name: 'Wallets & Small Leather Goods',
    slug: 'wallets-small-leather-goods',
    description: 'French vegetable-tanned cardholders, bifold wallets, and passport cases hand-stitched with waxed linen thread.',
    image: '/images/luxury/prod-wallet-1.webp',
    displayPriority: 70,
    isActive: true,
  },
  {
    id: 'cat-belts',
    name: 'Belts & Accessories',
    slug: 'belts-accessories',
    description: 'Solid brass and palladium hardware mounted on bridle leather straps and handcrafted accessories.',
    image: '/images/luxury/prod-belt-1.webp',
    displayPriority: 60,
    isActive: true,
  },
  {
    id: 'cat-waitlist',
    name: 'Waitlist & Bespoke',
    slug: 'waitlist',
    description: 'Exclusive atelier pre-order allocations, bespoke commissions, and limited vault creations available by private waitlist invitation.',
    image: '/images/luxury/hero-campaign.webp',
    displayPriority: 50,
    isActive: true,
  },
];

// ---------------------------------------------------------------------------
// Shoe Subcategories
// ---------------------------------------------------------------------------
export const SHOE_SUBCATEGORIES: Category[] = [
  {
    id: 'cat-shoes-oxford',
    name: 'Oxford Shoes',
    slug: 'shoes-oxford',
    description: 'Closed-lacing Goodyear-welted Oxford dress shoes in mirror-burnished French box calfskin. Shown as complete matching pairs.',
    image: '/images/luxury/prod-shoe-oxford-pair.webp',
    displayPriority: 89,
    isActive: true,
  },
  {
    id: 'cat-shoes-chelsea',
    name: 'Chelsea Boots',
    slug: 'shoes-chelsea',
    description: 'Architectural wholecut Chelsea boots in full-grain Florentine calfskin with storm-welted weather resistance.',
    image: '/images/luxury/prod-shoe-chelsea-pair.webp',
    displayPriority: 88,
    isActive: true,
  },
  {
    id: 'cat-shoes-derby',
    name: 'Derby Shoes',
    slug: 'shoes-derby',
    description: 'Open-lacing derby silhouettes in vegetable-tanned calf. Versatile enough for City or country.',
    image: '/images/luxury/prod-shoe-casualderby-pair.webp',
    displayPriority: 87,
    isActive: true,
  },
  {
    id: 'cat-shoes-loafer',
    name: 'Loafers',
    slug: 'shoes-loafer',
    description: 'Hand-sewn penny and tassel loafers in buttery soft calfskin with flexible leather soles.',
    image: '/images/luxury/prod-shoe-loafer-pair.webp',
    displayPriority: 86,
    isActive: true,
  },
  {
    id: 'cat-shoes-monk',
    name: 'Monk Straps',
    slug: 'shoes-monk',
    description: 'Single and double monk strap shoes with solid brass buckles and Goodyear-welted construction.',
    image: '/images/luxury/prod-shoe-monk-pair.webp',
    displayPriority: 85,
    isActive: true,
  },
  {
    id: 'cat-shoes-boots',
    name: 'Dress Boots',
    slug: 'shoes-boots',
    description: 'Lace-up dress boots in full-grain calf and antiqued leathers with storm-welted soles.',
    image: '/images/luxury/prod-shoe-dressboot-pair.webp',
    displayPriority: 84,
    isActive: true,
  },
];

// ---------------------------------------------------------------------------
// Bag Subcategories
// ---------------------------------------------------------------------------
export const BAG_SUBCATEGORIES: Category[] = [
  {
    id: 'cat-bags-laptop',
    name: 'Laptop Bags & Briefcases',
    slug: 'bags-laptop',
    description: 'Structured full-grain leather briefcases and laptop bags built for daily City use.',
    image: '/images/luxury/prod-briefcase-1.webp',
    displayPriority: 79,
    isActive: true,
  },
  {
    id: 'cat-bags-handbag',
    name: 'Handbags & Totes',
    slug: 'bags-handbag',
    description: 'Architectural totes and handbags in pebbled full-grain cowhide with brass hardware.',
    image: '/images/luxury/prod-tote-1.webp',
    displayPriority: 78,
    isActive: true,
  },
  {
    id: 'cat-bags-weekender',
    name: 'Weekender & Duffel',
    slug: 'bags-weekender',
    description: 'Executive travel duffels and weekender bags engineered to international carry-on dimensions.',
    image: '/images/luxury/prod-weekender-1.webp',
    displayPriority: 77,
    isActive: true,
  },
  {
    id: 'cat-bags-backpack',
    name: 'Backpacks',
    slug: 'bags-backpack',
    description: 'Full-grain leather rucksacks combining function with refined atelier aesthetics.',
    image: '/images/luxury/prod-weekender-2.webp',
    displayPriority: 76,
    isActive: true,
  },
  {
    id: 'cat-bags-messenger',
    name: 'Messenger Bags',
    slug: 'bags-messenger',
    description: 'Single-strap messenger bags in bridle leather with adjustable canvas webbing straps.',
    image: '/images/luxury/prod-briefcase-2.webp',
    displayPriority: 75,
    isActive: true,
  },
];

// All subcategories combined (for seed/utility use)
export const ALL_SUBCATEGORIES: Category[] = [
  ...SHOE_SUBCATEGORIES,
  ...BAG_SUBCATEGORIES,
];

export const INITIAL_PRODUCTS: Product[] = [
  // 1. The Sovereign Biker Jacket
  {
    id: 'prod-sovereign-biker',
    title: 'The Sovereign Biker Jacket',
    slug: 'the-sovereign-biker-jacket',
    styleCode: 'ACM-JKT-001',
    description: 'A monument to British tailoring and rebellious distinction. Handcrafted from heavy 1.2mm Italian full-grain vegetable-tanned steerhide, featuring custom brushed palladium hardware, asymmetric front zip, and silk-cupro interior lining.',
    craftNotes: 'Cut by hand in our London atelier. Each panel is individually hand-glazed with organic beeswax to yield a lustrous deep obsidian patina that matures uniquely with its wearer.',
    careDetails: 'Specialist leather clean only. Store on wide contoured cedar hanger in breathable garment bag. Condition annually with organic beeswax leather balm.',
    sizeChartImage: '/images/size-charts/jacket_size_chart.svg',
    leatherGrade: 'Italian Full-Grain Steerhide (1.2mm Waxed)',
    material: 'Full-Grain Steerhide & Silk Cupro',
    colorFamily: 'Black',
    priceInPence: 185000, // £1,850.00
    currency: 'GBP',
    status: 'ACTIVE',
    isTopSelling: true,
    isNewArrival: false,
    isFeaturedHero: true,
    displayPriority: 100,
    categoryId: 'cat-jackets',
    metaTitle: 'The Sovereign Biker Jacket | ACEMEN London',
    metaDescription: 'Handcrafted British luxury motorcycle jacket in 1.2mm Italian full-grain steerhide with brushed palladium hardware.',
    images: [
      {
        id: 'img-jkt-1',
        url: '/images/luxury/prod-jacket-classic-1.webp',
        altText: 'ACEMEN The Sovereign Biker Jacket front view',
        position: 0,
        isPrimary: true,
      },
      {
        id: 'img-jkt-2',
        url: '/images/luxury/prod-jacket-bomber-1.webp',
        altText: 'ACEMEN The Sovereign Biker Jacket tailored back view',
        position: 1,
        isPrimary: false,
      },
    ],
    variants: [
      {
        id: 'var-jkt-1',
        sku: 'ACM-JKT-001-38R',
        size: '38R / Small',
        color: 'Obsidian Black',
        colorHex: '#111111',
        stockQuantity: 4,
        isActive: true,
        displayPriority: 1,
        productId: 'prod-sovereign-biker',
      },
      {
        id: 'var-jkt-2',
        sku: 'ACM-JKT-001-40R',
        size: '40R / Medium',
        color: 'Obsidian Black',
        colorHex: '#111111',
        stockQuantity: 7,
        isActive: true,
        displayPriority: 2,
        productId: 'prod-sovereign-biker',
      },
      {
        id: 'var-jkt-3',
        sku: 'ACM-JKT-001-42R',
        size: '42R / Large',
        color: 'Obsidian Black',
        colorHex: '#111111',
        stockQuantity: 5,
        isActive: true,
        displayPriority: 3,
        productId: 'prod-sovereign-biker',
      },
      {
        id: 'var-jkt-4',
        sku: 'ACM-JKT-001-44R',
        size: '44R / Extra Large (XL)',
        color: 'Obsidian Black',
        colorHex: '#111111',
        stockQuantity: 4,
        isActive: true,
        displayPriority: 4,
        productId: 'prod-sovereign-biker',
      },
      {
        id: 'var-jkt-5',
        sku: 'ACM-JKT-001-46R',
        size: '46R / XXL',
        color: 'Obsidian Black',
        colorHex: '#111111',
        stockQuantity: 3,
        isActive: true,
        displayPriority: 5,
        productId: 'prod-sovereign-biker',
      },
    ],
  },

  // 2. The Elysian Shearling Aviator
  {
    id: 'prod-elysian-shearling',
    title: 'The Elysian Shearling Aviator',
    slug: 'the-elysian-shearling-aviator',
    styleCode: 'ACM-JKT-002',
    description: 'An uncompromising cold-weather triumph. Engineered from dense Spanish Merino shearling with a distressed oiled calfskin exterior. Accented with brass roller buckles at the collar and waistband.',
    craftNotes: 'Sourced from heritage tanneries in Catalonia. Hand-stitched with reinforced welted seams and thermal retention tested down to -15°C.',
    careDetails: 'Specialist fur and shearling dry clean only. Avoid prolonged moisture exposure. Brush collar gently with brass suede brush.',
    sizeChartImage: '/images/size-charts/jacket_size_chart.svg',
    leatherGrade: 'Catalan Spanish Merino Shearling & Oiled Calfskin',
    material: 'Natural Shearling Fur & Oiled Calfskin',
    colorFamily: 'Brown',
    priceInPence: 245000, // £2,450.00
    currency: 'GBP',
    status: 'ACTIVE',
    isTopSelling: true,
    isNewArrival: true,
    isFeaturedHero: true,
    displayPriority: 90,
    categoryId: 'cat-jackets',
    metaTitle: 'The Elysian Shearling Aviator | ACEMEN London',
    metaDescription: 'Authentic Spanish Merino shearling flight jacket with oiled calfskin exterior and solid brass roller buckles.',
    images: [
      {
        id: 'img-avi-1',
        url: '/images/luxury/prod-jacket-bomber-1.webp',
        altText: 'ACEMEN The Elysian Shearling Aviator jacket front view',
        position: 0,
        isPrimary: true,
      },
      {
        id: 'img-avi-2',
        url: '/images/luxury/prod-jacket-classic-1.webp',
        altText: 'ACEMEN The Elysian Shearling Aviator jacket back view',
        position: 1,
        isPrimary: false,
      },
    ],
    variants: [
      {
        id: 'var-avi-1',
        sku: 'ACM-JKT-002-38R',
        size: '38R / Small',
        color: 'Espresso Brown',
        colorHex: '#3D2817',
        stockQuantity: 3,
        isActive: true,
        displayPriority: 1,
        productId: 'prod-elysian-shearling',
      },
      {
        id: 'var-avi-2',
        sku: 'ACM-JKT-002-40R',
        size: '40R / Medium',
        color: 'Espresso Brown',
        colorHex: '#3D2817',
        stockQuantity: 6,
        isActive: true,
        displayPriority: 2,
        productId: 'prod-elysian-shearling',
      },
      {
        id: 'var-avi-3',
        sku: 'ACM-JKT-002-42R',
        size: '42R / Large',
        color: 'Espresso Brown',
        colorHex: '#3D2817',
        stockQuantity: 4,
        isActive: true,
        displayPriority: 3,
        productId: 'prod-elysian-shearling',
      },
      {
        id: 'var-avi-4',
        sku: 'ACM-JKT-002-44R',
        size: '44R / Extra Large (XL)',
        color: 'Espresso Brown',
        colorHex: '#3D2817',
        stockQuantity: 5,
        isActive: true,
        displayPriority: 4,
        productId: 'prod-elysian-shearling',
      },
      {
        id: 'var-avi-5',
        sku: 'ACM-JKT-002-46R',
        size: '46R / XXL',
        color: 'Espresso Brown',
        colorHex: '#3D2817',
        stockQuantity: 3,
        isActive: true,
        displayPriority: 5,
        productId: 'prod-elysian-shearling',
      },
    ],
  },

  // 3. The Cadogan Oxford Dress Shoes (Complete Matching Pair)
  {
    id: 'prod-cadogan-oxford',
    title: 'The Cadogan Oxford Dress Shoe',
    slug: 'the-cadogan-oxford-dress-shoe',
    styleCode: 'ACM-SH-001',
    description: 'The pinnacle of Northamptonshire shoemaking. Closed-channel Goodyear-welted dress shoes shaped over our bespoke chisel-toe last, executed in mirror-burnished French box calfskin.',
    craftNotes: 'Constructed across 212 independent manual steps. Features oak-bark tanned leather soles and hand-pegged waist fiddlebacks.',
    careDetails: 'Always insert cedar shoe trees immediately after wear. Polish regularly with beeswax cream and finish with high-gloss mirror glaze on toe cap.',
    sizeChartImage: '/images/size-charts/shoe_size_chart.svg',
    leatherGrade: 'French Box Calfskin (Annonay Tannery)',
    material: 'Box Calfskin & Oak Bark Leather Sole',
    colorFamily: 'Black',
    priceInPence: 68000, // £680.00
    currency: 'GBP',
    status: 'ACTIVE',
    isTopSelling: true,
    isNewArrival: false,
    isFeaturedHero: false,
    displayPriority: 85,
    categoryId: 'cat-shoes',
    metaTitle: 'The Cadogan Oxford Dress Shoe | ACEMEN Footwear',
    metaDescription: 'Goodyear-welted British formal Oxford shoes in French box calfskin. Shown as complete matching pair.',
    images: [
      {
        id: 'img-ox-1',
        url: '/images/luxury/prod-shoe-oxford-pair.webp',
        altText: 'ACEMEN The Cadogan Oxford dress shoes complete matching pair front angle',
        position: 0,
        isPrimary: true,
      },
      {
        id: 'img-ox-2',
        url: '/images/luxury/prod-oxford-1.webp',
        altText: 'ACEMEN The Cadogan Oxford dress shoes single profile view',
        position: 1,
        isPrimary: false,
      },
    ],
    variants: [
      {
        id: 'var-ox-7',
        sku: 'ACM-SH-001-UK7',
        size: 'UK 7 / US 8 / EU 41',
        color: 'Mirror Obsidian',
        colorHex: '#111111',
        stockQuantity: 4,
        isActive: true,
        displayPriority: 1,
        productId: 'prod-cadogan-oxford',
      },
      {
        id: 'var-ox-8',
        sku: 'ACM-SH-001-UK8',
        size: 'UK 8 / US 9 / EU 42',
        color: 'Mirror Obsidian',
        colorHex: '#111111',
        stockQuantity: 5,
        isActive: true,
        displayPriority: 2,
        productId: 'prod-cadogan-oxford',
      },
      {
        id: 'var-ox-9',
        sku: 'ACM-SH-001-UK9',
        size: 'UK 9 / US 10 / EU 43',
        color: 'Mirror Obsidian',
        colorHex: '#111111',
        stockQuantity: 8,
        isActive: true,
        displayPriority: 3,
        productId: 'prod-cadogan-oxford',
      },
      {
        id: 'var-ox-10',
        sku: 'ACM-SH-001-UK10',
        size: 'UK 10 / US 11 / EU 44',
        color: 'Mirror Obsidian',
        colorHex: '#111111',
        stockQuantity: 6,
        isActive: true,
        displayPriority: 4,
        productId: 'prod-cadogan-oxford',
      },
      {
        id: 'var-ox-11',
        sku: 'ACM-SH-001-UK11',
        size: 'UK 11 / US 12 / EU 45',
        color: 'Mirror Obsidian',
        colorHex: '#111111',
        stockQuantity: 3,
        isActive: true,
        displayPriority: 5,
        productId: 'prod-cadogan-oxford',
      },
    ],
  },

  // 4. The Mayfair Chelsea Boot (Complete Matching Pair)
  {
    id: 'prod-mayfair-chelsea',
    title: 'The Mayfair Chelsea Boot',
    slug: 'the-mayfair-chelsea-boot',
    styleCode: 'ACM-SH-002',
    description: 'An architectural silhouette carved from a single piece of full-grain Florentine calfskin. Finished with tonal woven pull tabs, reinforced elastic gussets, and storm-welted weather resistance.',
    craftNotes: 'Wholecut front construction with zero external forward seams. Lined entirely in glove-soft natural vegetable-tanned calf.',
    careDetails: 'Clean with damp cloth and nourish with neutral beeswax conditioner. Store with tall cedar boot trees.',
    sizeChartImage: '/images/size-charts/shoe_size_chart.svg',
    leatherGrade: 'Full-Grain Florentine Calfskin',
    material: 'Calfskin & Storm-Welted Leather Sole',
    colorFamily: 'Brown',
    priceInPence: 74000, // £740.00
    currency: 'GBP',
    status: 'ACTIVE',
    isTopSelling: true,
    isNewArrival: true,
    isFeaturedHero: false,
    displayPriority: 80,
    categoryId: 'cat-shoes',
    metaTitle: 'The Mayfair Chelsea Boot | ACEMEN Footwear',
    metaDescription: 'Wholecut Florentine calfskin Chelsea boots with Goodyear welted sole. Shown as complete matching pair.',
    images: [
      {
        id: 'img-ch-1',
        url: '/images/luxury/prod-shoe-chelsea-pair.webp',
        altText: 'ACEMEN The Mayfair Chelsea boots complete matching pair front angle',
        position: 0,
        isPrimary: true,
      },
      {
        id: 'img-ch-2',
        url: '/images/luxury/prod-chelsea-1.webp',
        altText: 'ACEMEN The Mayfair Chelsea boot side profile view',
        position: 1,
        isPrimary: false,
      },
    ],
    variants: [
      {
        id: 'var-ch-7',
        sku: 'ACM-SH-002-UK7',
        size: 'UK 7 / US 8 / EU 41',
        color: 'Dark Espresso',
        colorHex: '#38251B',
        stockQuantity: 3,
        isActive: true,
        displayPriority: 1,
        productId: 'prod-mayfair-chelsea',
      },
      {
        id: 'var-ch-8',
        sku: 'ACM-SH-002-UK8',
        size: 'UK 8 / US 9 / EU 42',
        color: 'Dark Espresso',
        colorHex: '#38251B',
        stockQuantity: 4,
        isActive: true,
        displayPriority: 2,
        productId: 'prod-mayfair-chelsea',
      },
      {
        id: 'var-ch-9',
        sku: 'ACM-SH-002-UK9',
        size: 'UK 9 / US 10 / EU 43',
        color: 'Dark Espresso',
        colorHex: '#38251B',
        stockQuantity: 6,
        isActive: true,
        displayPriority: 3,
        productId: 'prod-mayfair-chelsea',
      },
      {
        id: 'var-ch-10',
        sku: 'ACM-SH-002-UK10',
        size: 'UK 10 / US 11 / EU 44',
        color: 'Dark Espresso',
        colorHex: '#38251B',
        stockQuantity: 5,
        isActive: true,
        displayPriority: 4,
        productId: 'prod-mayfair-chelsea',
      },
      {
        id: 'var-ch-11',
        sku: 'ACM-SH-002-UK11',
        size: 'UK 11 / US 12 / EU 45',
        color: 'Dark Espresso',
        colorHex: '#38251B',
        stockQuantity: 2,
        isActive: true,
        displayPriority: 5,
        productId: 'prod-mayfair-chelsea',
      },
    ],
  },

  // 5. The Kensington Weekender Duffel
  {
    id: 'prod-kensington-duffel',
    title: 'The Kensington Weekender Duffel',
    slug: 'the-kensington-weekender-duffel',
    styleCode: 'ACM-BAG-001',
    description: 'An executive travel piece engineered to international carry-on dimensions. Built from structured pebbled full-grain leather with solid brass palladium-plated hardware and reinforced load-bearing handles.',
    craftNotes: 'Hand-sewn rolled top handles and double-layered base with protective brass feet. Internal padded laptop sleeve and waterproof shoe compartment.',
    careDetails: 'Wipe clean with microfibre cloth. Condition leather biannually. Protect interior canvas with scotchguard.',
    leatherGrade: 'Heavy Pebbled Full-Grain Cowhide',
    material: 'Full-Grain Leather & Heavyweight British Canvas Lining',
    colorFamily: 'Black',
    priceInPence: 125000, // £1,250.00
    currency: 'GBP',
    status: 'ACTIVE',
    isTopSelling: false,
    isNewArrival: true,
    isFeaturedHero: false,
    displayPriority: 75,
    categoryId: 'cat-bags',
    metaTitle: 'The Kensington Weekender Duffel | ACEMEN Bags',
    metaDescription: 'Bespoke full-grain pebbled leather weekender duffel with brushed palladium hardware.',
    images: [
      {
        id: 'img-duf-1',
        url: '/images/luxury/prod-weekender-1.webp',
        altText: 'ACEMEN The Kensington Weekender duffel front view',
        position: 0,
        isPrimary: true,
      },
      {
        id: 'img-duf-2',
        url: '/images/luxury/prod-weekender-2.webp',
        altText: 'ACEMEN The Kensington Weekender duffel side perspective view',
        position: 1,
        isPrimary: false,
      },
    ],
    variants: [
      {
        id: 'var-duf-1',
        sku: 'ACM-BAG-001-STD',
        size: 'One Size (45L)',
        color: 'Obsidian Black',
        colorHex: '#111111',
        stockQuantity: 8,
        isActive: true,
        displayPriority: 1,
        productId: 'prod-kensington-duffel',
      },
    ],
  },

  // 6. The Belgravia Cardholder
  {
    id: 'prod-belgravia-cardholder',
    title: 'The Belgravia Cardholder',
    slug: 'the-belgravia-cardholder',
    styleCode: 'ACM-WLT-001',
    description: 'An ultra-slim everyday essential. Crafted from French vegetable-tanned calfskin with hand-creased and edge-burnished perimeter stitching. Features four card slots and a central currency slip.',
    craftNotes: 'Each pocket is meticulously skived down to 0.4mm to maintain a razor-thin 3mm profile even when fully loaded with cards and notes.',
    careDetails: 'Avoid submerging in liquids. Treat occasionally with delicate leather cream.',
    leatherGrade: 'French Vegetable-Tanned Box Calfskin',
    material: 'Full-Grain Vegetable Tanned Calfskin',
    colorFamily: 'Black',
    priceInPence: 22000, // £220.00
    currency: 'GBP',
    status: 'ACTIVE',
    isTopSelling: false,
    isNewArrival: false,
    isFeaturedHero: false,
    displayPriority: 70,
    categoryId: 'cat-wallets',
    metaTitle: 'The Belgravia Cardholder | ACEMEN Small Leather Goods',
    metaDescription: 'Ultra-slim French vegetable-tanned calfskin cardholder with hand-painted edges.',
    images: [
      {
        id: 'img-wlt-1',
        url: '/images/luxury/prod-cardholder-1.webp',
        altText: 'ACEMEN The Belgravia Cardholder flat lay view',
        position: 0,
        isPrimary: true,
      },
      {
        id: 'img-wlt-2',
        url: '/images/luxury/prod-cardholder-2.webp',
        altText: 'ACEMEN The Belgravia Cardholder saddle stitching detail',
        position: 1,
        isPrimary: false,
      },
    ],
    variants: [
      {
        id: 'var-wlt-1',
        sku: 'ACM-WLT-001-STD',
        size: 'Standard (10cm x 7cm)',
        color: 'Obsidian Black',
        colorHex: '#111111',
        stockQuantity: 15,
        isActive: true,
        displayPriority: 1,
        productId: 'prod-belgravia-cardholder',
      },
    ],
  },

  // 7. The Marylebone Derby Brogue
  {
    id: 'prod-marylebone-derby',
    title: 'The Marylebone Derby Brogue',
    slug: 'the-marylebone-derby-brogue',
    styleCode: 'ACM-SH-003',
    description: 'Open-lacing brogue silhouette in rich chocolate full-grain calfskin. Defined by hand-punched wingtip medallions and Goodyear-welted storm construction. Versatile enough for City boardrooms and country estates alike.',
    craftNotes: 'Each brogue perforation is hand-punched by master craftsmen in our Northamptonshire workshop. The open-lacing derby construction allows generous fitting across all widths.',
    careDetails: 'Polish with matching shade cream. Use cedar shoe trees immediately after wear. Re-sole at 18-month intervals at our London atelier.',
    leatherGrade: 'Full-Grain Chocolate Calfskin (Annonay Tannery)',
    material: 'Full-Grain Calfskin & Oak Bark Leather Sole',
    colorFamily: 'Brown',
    priceInPence: 72000, // £720.00
    currency: 'GBP',
    status: 'ACTIVE',
    isTopSelling: false,
    isNewArrival: true,
    isFeaturedHero: false,
    displayPriority: 82,
    categoryId: 'cat-shoes-derby',
    metaTitle: 'The Marylebone Derby Brogue | ACEMEN Footwear',
    metaDescription: 'Goodyear-welted hand-punched brogue derby shoe in full-grain Annonay calfskin. Northamptonshire craftsmanship.',
    images: [
      {
        id: 'img-drb-1',
        url: '/images/luxury/prod-shoe-casualderby-pair.webp',
        altText: 'ACEMEN Marylebone Derby Brogue pair on marble',
        position: 0,
        isPrimary: true,
      },
    ],
    variants: [
      { id: 'var-drb-1', sku: 'ACM-SH-003-7', size: 'UK 7 / US 8 / EU 41', color: 'Chocolate Brown', colorHex: '#3D1F0A', stockQuantity: 5, isActive: true, displayPriority: 1, productId: 'prod-marylebone-derby' },
      { id: 'var-drb-2', sku: 'ACM-SH-003-8', size: 'UK 8 / US 9 / EU 42', color: 'Chocolate Brown', colorHex: '#3D1F0A', stockQuantity: 8, isActive: true, displayPriority: 2, productId: 'prod-marylebone-derby' },
      { id: 'var-drb-3', sku: 'ACM-SH-003-9', size: 'UK 9 / US 10 / EU 43', color: 'Chocolate Brown', colorHex: '#3D1F0A', stockQuantity: 6, isActive: true, displayPriority: 3, productId: 'prod-marylebone-derby' },
      { id: 'var-drb-4', sku: 'ACM-SH-003-10', size: 'UK 10 / US 11 / EU 44', color: 'Chocolate Brown', colorHex: '#3D1F0A', stockQuantity: 3, isActive: true, displayPriority: 4, productId: 'prod-marylebone-derby' },
      { id: 'var-drb-5', sku: 'ACM-SH-003-11', size: 'UK 11 / US 12 / EU 45', color: 'Chocolate Brown', colorHex: '#3D1F0A', stockQuantity: 2, isActive: true, displayPriority: 5, productId: 'prod-marylebone-derby' },
    ],
  },

  // 8. The Mayfair Cognac Loafer
  {
    id: 'prod-mayfair-loafer',
    title: 'The Mayfair Cognac Loafer',
    slug: 'the-mayfair-cognac-loafer',
    styleCode: 'ACM-SH-004',
    description: 'Hand-sewn moccasin construction in warm cognac calfskin. The signature brass coin medallion at the vamp is hand-cast in solid brass and polished to a mirror sheen. Flexible leather sole with rubber tread insert.',
    craftNotes: 'The upper is wet-moulded over the last for 72 hours before assembly, ensuring a glove-like fit from the first wear.',
    careDetails: 'Condition monthly with matching cognac leather cream. Use shoe bags when travelling. Avoid prolonged wet conditions.',
    leatherGrade: 'Cognac Full-Grain Calfskin',
    material: 'Full-Grain Calfskin & Flexible Leather Sole',
    colorFamily: 'Tan',
    priceInPence: 58000, // £580.00
    currency: 'GBP',
    status: 'ACTIVE',
    isTopSelling: true,
    isNewArrival: false,
    isFeaturedHero: false,
    displayPriority: 81,
    categoryId: 'cat-shoes-loafer',
    metaTitle: 'The Mayfair Cognac Loafer | ACEMEN Footwear',
    metaDescription: 'Hand-sewn cognac calfskin penny loafer with solid brass coin medallion. London atelier.',
    images: [
      {
        id: 'img-lof-1',
        url: '/images/luxury/prod-shoe-loafer-pair.webp',
        altText: 'ACEMEN Mayfair Cognac Loafer pair on stone',
        position: 0,
        isPrimary: true,
      },
    ],
    variants: [
      { id: 'var-lof-1', sku: 'ACM-SH-004-7', size: 'UK 7 / US 8 / EU 41', color: 'Cognac Tan', colorHex: '#B8763D', stockQuantity: 7, isActive: true, displayPriority: 1, productId: 'prod-mayfair-loafer' },
      { id: 'var-lof-2', sku: 'ACM-SH-004-8', size: 'UK 8 / US 9 / EU 42', color: 'Cognac Tan', colorHex: '#B8763D', stockQuantity: 10, isActive: true, displayPriority: 2, productId: 'prod-mayfair-loafer' },
      { id: 'var-lof-3', sku: 'ACM-SH-004-9', size: 'UK 9 / US 10 / EU 43', color: 'Cognac Tan', colorHex: '#B8763D', stockQuantity: 6, isActive: true, displayPriority: 3, productId: 'prod-mayfair-loafer' },
      { id: 'var-lof-4', sku: 'ACM-SH-004-10', size: 'UK 10 / US 11 / EU 44', color: 'Cognac Tan', colorHex: '#B8763D', stockQuantity: 2, isActive: true, displayPriority: 4, productId: 'prod-mayfair-loafer' },
      { id: 'var-lof-5', sku: 'ACM-SH-004-11', size: 'UK 11 / US 12 / EU 45', color: 'Cognac Tan', colorHex: '#B8763D', stockQuantity: 3, isActive: true, displayPriority: 5, productId: 'prod-mayfair-loafer' },
    ],
  },

  // 9. The Westminster Double Monk
  {
    id: 'prod-westminster-monk',
    title: 'The Westminster Double Monk',
    slug: 'the-westminster-double-monk',
    styleCode: 'ACM-SH-005',
    description: 'Architectural double-buckle monk strap in deep espresso calfskin. Solid cast-brass buckles with a satin-brushed finish. Cap-toe seam adds structural drama to the chisel silhouette.',
    craftNotes: 'The twin-buckle closure is a hallmark of Continental elegance — no lacing, no compromise. Storm-welted and finished with 240-step hand-burnishing.',
    careDetails: 'Condition with dark espresso leather cream. Polish buckles with soft brass cloth. Insert cedar trees after each wear.',
    leatherGrade: 'Dark Espresso Full-Grain Calfskin',
    material: 'Full-Grain Calfskin & Goodyear Welt',
    colorFamily: 'Dark Brown',
    priceInPence: 78000, // £780.00
    currency: 'GBP',
    status: 'ACTIVE',
    isTopSelling: false,
    isNewArrival: true,
    isFeaturedHero: false,
    displayPriority: 80,
    categoryId: 'cat-shoes-monk',
    metaTitle: 'The Westminster Double Monk Strap | ACEMEN Footwear',
    metaDescription: 'Goodyear-welted double monk strap in espresso calfskin with solid brass buckles.',
    images: [
      {
        id: 'img-mnk-1',
        url: '/images/luxury/prod-shoe-monk-pair.webp',
        altText: 'ACEMEN Westminster Double Monk strap shoes pair',
        position: 0,
        isPrimary: true,
      },
    ],
    variants: [
      { id: 'var-mnk-1', sku: 'ACM-SH-005-7', size: 'UK 7 / US 8 / EU 41', color: 'Espresso Dark Brown', colorHex: '#2A1208', stockQuantity: 4, isActive: true, displayPriority: 1, productId: 'prod-westminster-monk' },
      { id: 'var-mnk-2', sku: 'ACM-SH-005-8', size: 'UK 8 / US 9 / EU 42', color: 'Espresso Dark Brown', colorHex: '#2A1208', stockQuantity: 7, isActive: true, displayPriority: 2, productId: 'prod-westminster-monk' },
      { id: 'var-mnk-3', sku: 'ACM-SH-005-9', size: 'UK 9 / US 10 / EU 43', color: 'Espresso Dark Brown', colorHex: '#2A1208', stockQuantity: 5, isActive: true, displayPriority: 3, productId: 'prod-westminster-monk' },
      { id: 'var-mnk-4', sku: 'ACM-SH-005-10', size: 'UK 10 / US 11 / EU 44', color: 'Espresso Dark Brown', colorHex: '#2A1208', stockQuantity: 3, isActive: true, displayPriority: 4, productId: 'prod-westminster-monk' },
      { id: 'var-mnk-5', sku: 'ACM-SH-005-11', size: 'UK 11 / US 12 / EU 45', color: 'Espresso Dark Brown', colorHex: '#2A1208', stockQuantity: 2, isActive: true, displayPriority: 5, productId: 'prod-westminster-monk' },
    ],
  },

  // 10. The Knightsbridge Dress Boot
  {
    id: 'prod-knightsbridge-boot',
    title: 'The Knightsbridge Dress Boot',
    slug: 'the-knightsbridge-dress-boot',
    styleCode: 'ACM-SH-006',
    description: 'A refined lace-up dress boot that bridges formal and field with authority. Executed in midnight black full-grain calfskin with storm-welted Goodyear construction. The seven-eyelet profile provides commanding ankle structure.',
    craftNotes: 'The military-inspired last is exclusive to ACEMEN. Hand-lasted over 96 hours and finished with a high-shine toe cap mirror glaze.',
    careDetails: 'Polish with black wax cream. Treat welt seam annually with saddle soap. Insert shoe trees after every wear.',
    leatherGrade: 'Midnight Black Full-Grain Calfskin',
    material: 'Full-Grain Calfskin & Storm-Welted Sole',
    colorFamily: 'Black',
    priceInPence: 86000, // £860.00
    currency: 'GBP',
    status: 'ACTIVE',
    isTopSelling: false,
    isNewArrival: false,
    isFeaturedHero: false,
    displayPriority: 79,
    categoryId: 'cat-shoes-boots',
    metaTitle: 'The Knightsbridge Dress Boot | ACEMEN Footwear',
    metaDescription: 'Storm-welted Goodyear dress boot in midnight black calfskin with military-inspired construction.',
    images: [
      {
        id: 'img-kbt-1',
        url: '/images/luxury/prod-shoe-dressboot-pair.webp',
        altText: 'ACEMEN Knightsbridge Dress Boot pair on marble',
        position: 0,
        isPrimary: true,
      },
    ],
    variants: [
      { id: 'var-kbt-1', sku: 'ACM-SH-006-7', size: 'UK 7 / US 8 / EU 41', color: 'Midnight Black', colorHex: '#0A0A0A', stockQuantity: 4, isActive: true, displayPriority: 1, productId: 'prod-knightsbridge-boot' },
      { id: 'var-kbt-2', sku: 'ACM-SH-006-8', size: 'UK 8 / US 9 / EU 42', color: 'Midnight Black', colorHex: '#0A0A0A', stockQuantity: 6, isActive: true, displayPriority: 2, productId: 'prod-knightsbridge-boot' },
      { id: 'var-kbt-3', sku: 'ACM-SH-006-9', size: 'UK 9 / US 10 / EU 43', color: 'Midnight Black', colorHex: '#0A0A0A', stockQuantity: 5, isActive: true, displayPriority: 3, productId: 'prod-knightsbridge-boot' },
      { id: 'var-kbt-4', sku: 'ACM-SH-006-10', size: 'UK 10 / US 11 / EU 44', color: 'Midnight Black', colorHex: '#0A0A0A', stockQuantity: 2, isActive: true, displayPriority: 4, productId: 'prod-knightsbridge-boot' },
      { id: 'var-kbt-5', sku: 'ACM-SH-006-11', size: 'UK 11 / US 12 / EU 45', color: 'Midnight Black', colorHex: '#0A0A0A', stockQuantity: 3, isActive: true, displayPriority: 5, productId: 'prod-knightsbridge-boot' },
    ],
  },

  // 11. The City Leather Briefcase
  {
    id: 'prod-city-briefcase',
    title: 'The City Leather Briefcase',
    slug: 'the-city-leather-briefcase',
    styleCode: 'ACM-BG-003',
    description: 'Structured single-compartment briefcase in warm cognac full-grain leather. Fits a 15" laptop and A4 documents. Brass stud feet, solid D-ring for optional strap, and antiqued brass turn-lock closure.',
    craftNotes: 'Hand-stitched with 0.8mm waxed linen thread. Full leather interior lining in matching cognac. Corner gussets are double-layered for structural integrity.',
    careDetails: 'Wipe with damp cloth only. Condition with neutral leather balm annually. Store with tissue paper padding when not in use.',
    leatherGrade: 'Cognac Vegetable-Tanned Full-Grain Cowhide',
    material: 'Full-Grain Cowhide & Brass Hardware',
    colorFamily: 'Tan',
    priceInPence: 49500, // £495.00
    currency: 'GBP',
    status: 'ACTIVE',
    isTopSelling: true,
    isNewArrival: false,
    isFeaturedHero: false,
    displayPriority: 76,
    categoryId: 'cat-bags-laptop',
    metaTitle: 'The City Leather Briefcase | ACEMEN Bags',
    metaDescription: 'Structured full-grain cognac leather briefcase with brass hardware. Fits 15" laptop.',
    images: [
      {
        id: 'img-bfc-1',
        url: '/images/luxury/prod-briefcase-1.webp',
        altText: 'ACEMEN City Leather Briefcase in cognac standing upright',
        position: 0,
        isPrimary: true,
      },
    ],
    variants: [
      { id: 'var-bfc-1', sku: 'ACM-BG-003-COG', size: 'One Size (38 x 28 x 10 cm)', color: 'Cognac Tan', colorHex: '#B8763D', stockQuantity: 8, isActive: true, displayPriority: 1, productId: 'prod-city-briefcase' },
    ],
  },

  // 12. The Kensington Structured Handbag
  {
    id: 'prod-kensington-handbag',
    title: 'The Kensington Structured Handbag',
    slug: 'the-kensington-structured-handbag',
    styleCode: 'ACM-BG-004',
    description: 'Architectural chocolate pebbled calfskin handbag. Trapeze silhouette with dual rolled leather handles and detachable shoulder strap. Gold-plated turn-lock and four solid base studs protect the base.',
    craftNotes: 'The silhouette is held rigid by a hand-bent internal steel frame — ensuring the architectural shape is preserved even when empty.',
    careDetails: 'Stuff with tissue paper when stored. Condition with neutral balm. Avoid contact with light-coloured fabrics.',
    leatherGrade: 'Pebbled Full-Grain Calfskin',
    material: 'Full-Grain Calfskin & Gold Hardware',
    colorFamily: 'Dark Brown',
    priceInPence: 67500, // £675.00
    currency: 'GBP',
    status: 'ACTIVE',
    isTopSelling: false,
    isNewArrival: true,
    isFeaturedHero: false,
    displayPriority: 75,
    categoryId: 'cat-bags-handbag',
    metaTitle: 'The Kensington Structured Handbag | ACEMEN Bags',
    metaDescription: 'Architectural pebbled calfskin handbag with gold-plated hardware and rigid internal frame.',
    images: [
      {
        id: 'img-hbg-1',
        url: '/images/luxury/prod-tote-1.webp',
        altText: 'ACEMEN Kensington Structured Handbag on marble plinth',
        position: 0,
        isPrimary: true,
      },
    ],
    variants: [
      { id: 'var-hbg-1', sku: 'ACM-BG-004-CHO', size: 'One Size (32 x 24 x 12 cm)', color: 'Chocolate Dark Brown', colorHex: '#2A1A0E', stockQuantity: 6, isActive: true, displayPriority: 1, productId: 'prod-kensington-handbag' },
    ],
  },

  // 13. The Fitzrovia Leather Backpack
  {
    id: 'prod-fitzrovia-backpack',
    title: 'The Fitzrovia Leather Backpack',
    slug: 'the-fitzrovia-leather-backpack',
    styleCode: 'ACM-BG-005',
    description: 'Architect-grade navy full-grain leather rucksack with padded laptop compartment. Solid brass antique-finish buckle closures. Padded back panel with moisture-wicking canvas. Hand-stitched reinforced base panel.',
    craftNotes: 'The triple-buckle closure system is rated for 40kg load bearing. Interior has dedicated 15" laptop sleeve and three organiser pockets.',
    careDetails: 'Wipe exterior with damp cloth. Condition brass hardware quarterly. Avoid overfilling to preserve strap integrity.',
    leatherGrade: 'Navy Full-Grain Leather',
    material: 'Full-Grain Leather & Canvas Lining',
    colorFamily: 'Navy',
    priceInPence: 44500, // £445.00
    currency: 'GBP',
    status: 'ACTIVE',
    isTopSelling: false,
    isNewArrival: true,
    isFeaturedHero: false,
    displayPriority: 74,
    categoryId: 'cat-bags-backpack',
    metaTitle: 'The Fitzrovia Leather Backpack | ACEMEN Bags',
    metaDescription: 'Full-grain navy leather backpack with solid brass hardware and padded laptop compartment.',
    images: [
      {
        id: 'img-bpk-1',
        url: '/images/luxury/prod-weekender-2.webp',
        altText: 'ACEMEN Fitzrovia Leather Backpack on marble plinth',
        position: 0,
        isPrimary: true,
      },
    ],
    variants: [
      { id: 'var-bpk-1', sku: 'ACM-BG-005-NAV', size: 'One Size (35 x 45 x 15 cm)', color: 'Navy Black', colorHex: '#1A1F2E', stockQuantity: 10, isActive: true, displayPriority: 1, productId: 'prod-fitzrovia-backpack' },
    ],
  },

  // 14. The Shoreditch Messenger
  {
    id: 'prod-shoreditch-messenger',
    title: 'The Shoreditch Messenger',
    slug: 'the-shoreditch-messenger',
    styleCode: 'ACM-BG-006',
    description: 'Rugged saddle-tan vegetable-tanned leather messenger bag with dual antiqued brass buckle closure. Wide adjustable canvas shoulder strap. Three external pockets and full main compartment with padded divider.',
    craftNotes: 'Vegetable-tanned leather is naturally water-resistant and develops a rich patina unique to each owner — it only improves with age and use.',
    careDetails: 'Allow to air dry naturally if wet. Oil with neatsfoot conditioner in winter. Brass fittings can be polished with standard brass cleaner.',
    leatherGrade: 'Saddle Tan Vegetable-Tanned Cowhide',
    material: 'Vegetable-Tanned Cowhide & Brass Hardware',
    colorFamily: 'Tan',
    priceInPence: 38500, // £385.00
    currency: 'GBP',
    status: 'ACTIVE',
    isTopSelling: true,
    isNewArrival: false,
    isFeaturedHero: false,
    displayPriority: 73,
    categoryId: 'cat-bags-messenger',
    metaTitle: 'The Shoreditch Messenger Bag | ACEMEN Bags',
    metaDescription: 'Saddle tan vegetable-tanned leather messenger bag with antique brass hardware.',
    images: [
      {
        id: 'img-msg-1',
        url: '/images/luxury/prod-briefcase-2.webp',
        altText: 'ACEMEN Shoreditch Messenger Bag on concrete',
        position: 0,
        isPrimary: true,
      },
    ],
    variants: [
      { id: 'var-msg-1', sku: 'ACM-BG-006-TAN', size: 'One Size (38 x 28 x 8 cm)', color: 'Saddle Tan', colorHex: '#B87333', stockQuantity: 12, isActive: true, displayPriority: 1, productId: 'prod-shoreditch-messenger' },
    ],
  },

  // 15. The Mayfair Bridle Belt
  {
    id: 'prod-mayfair-belt',
    title: 'The Mayfair Bridle Belt',
    slug: 'the-mayfair-bridle-belt',
    styleCode: 'ACM-BLT-001',
    description: 'Hand-cut from a single hide of dark chocolate English bridle leather. Solid cast-brass rectangular buckle with antique finish. 30mm width — the exact right proportion for formal trousers and business suits.',
    craftNotes: 'Bridle leather is traditional English tannage — impregnated with tallows and waxes for supreme weather resistance. Edges are hand-burnished over an open flame.',
    careDetails: 'Apply neatsfoot oil annually. Roll rather than fold when storing. Buckle can be repolished with brass cloth.',
    leatherGrade: 'English Bridle Leather (Sedgwick Tannery)',
    material: 'Bridle Leather & Solid Cast Brass',
    colorFamily: 'Dark Brown',
    priceInPence: 18500, // £185.00
    currency: 'GBP',
    status: 'ACTIVE',
    isTopSelling: false,
    isNewArrival: false,
    isFeaturedHero: false,
    displayPriority: 65,
    categoryId: 'cat-belts',
    metaTitle: 'The Mayfair Bridle Belt | ACEMEN Accessories',
    metaDescription: 'Hand-cut English bridle leather belt with solid brass buckle from Sedgwick tannery.',
    images: [
      {
        id: 'img-blt-1',
        url: '/images/luxury/prod-belt-1.webp',
        altText: 'ACEMEN Mayfair Bridle Belt coiled on marble surface',
        position: 0,
        isPrimary: true,
      },
    ],
    variants: [
      { id: 'var-blt-1', sku: 'ACM-BLT-001-30', size: '30" / 76cm', color: 'Dark Chocolate', colorHex: '#2A1208', stockQuantity: 8, isActive: true, displayPriority: 1, productId: 'prod-mayfair-belt' },
      { id: 'var-blt-2', sku: 'ACM-BLT-001-32', size: '32" / 81cm', color: 'Dark Chocolate', colorHex: '#2A1208', stockQuantity: 12, isActive: true, displayPriority: 2, productId: 'prod-mayfair-belt' },
      { id: 'var-blt-3', sku: 'ACM-BLT-001-34', size: '34" / 86cm', color: 'Dark Chocolate', colorHex: '#2A1208', stockQuantity: 10, isActive: true, displayPriority: 3, productId: 'prod-mayfair-belt' },
      { id: 'var-blt-4', sku: 'ACM-BLT-001-36', size: '36" / 91cm', color: 'Dark Chocolate', colorHex: '#2A1208', stockQuantity: 6, isActive: true, displayPriority: 4, productId: 'prod-mayfair-belt' },
      { id: 'var-blt-5', sku: 'ACM-BLT-001-38', size: '38" / 97cm', color: 'Dark Chocolate', colorHex: '#2A1208', stockQuantity: 4, isActive: true, displayPriority: 5, productId: 'prod-mayfair-belt' },
    ],
  },
  {
    id: 'prod-waitlist-shearling-holdall',
    title: 'The Sovereign Bespoke Shearling Holdall',
    slug: 'the-sovereign-bespoke-shearling-holdall',
    styleCode: 'ACM-WTL-001',
    description: 'An exceptional, limited-run private commission holdall crafted from hand-selected Spanish Merino shearling and bridle leather trim. Hand-stitched with waxed linen cord and finished with palladium hardware. Available exclusively by atelier waitlist reservation.',
    craftNotes: 'Each hide is individually selected and matched by our master leather cutter in London. Hand-set solid brass rivets and hand-buffed beeswax edges.',
    careDetails: 'Clean gently with natural wool brush. Condition smooth bridle leather accents biannually with ACEMEN Atelier Organic Leather Balm.',
    leatherGrade: 'Spanish Merino Shearling & English Bridle Hide (Sedgwick & Co)',
    material: 'Full-Grain Bridle Hide & Shearling',
    colorFamily: 'Chestnut & Ivory',
    priceInPence: 295000, // £2,950.00
    currency: 'GBP',
    status: 'WAITLIST',
    isTopSelling: false,
    isNewArrival: true,
    isFeaturedHero: false,
    displayPriority: 99,
    categoryId: 'cat-waitlist',
    metaTitle: 'The Sovereign Bespoke Shearling Holdall | ACEMEN Waitlist',
    metaDescription: 'Limited private allocation bespoke shearling holdall handcrafted in London. Available via atelier waitlist reservation.',
    images: [
      {
        id: 'img-wtl-1',
        url: '/images/luxury/acemen_travel_campaign_1788046267928.webp',
        altText: 'The Sovereign Bespoke Shearling Holdall on private tarmac',
        position: 0,
        isPrimary: true,
      },
      {
        id: 'img-wtl-2',
        url: '/images/luxury/prod-weekender-1.webp',
        altText: 'The Sovereign Holdall profile and hand-burnished edge detail',
        position: 1,
        isPrimary: false,
      },
      {
        id: 'img-wtl-3',
        url: '/images/luxury/prod-weekender-2.webp',
        altText: 'The Sovereign Holdall interior canvas lining and serial plate',
        position: 2,
        isPrimary: false,
      },
    ],
    variants: [
      {
        id: 'var-wtl-1',
        sku: 'ACM-WTL-001-STD',
        size: '55cm Weekend Carrier',
        color: 'Chestnut / Ivory Fleece',
        colorHex: '#3D2314',
        stockQuantity: 0, // Waitlist item
        isActive: true,
        displayPriority: 1,
        productId: 'prod-waitlist-shearling-holdall',
      },
      {
        id: 'var-wtl-2',
        sku: 'ACM-WTL-001-LRG',
        size: '65cm Continental Holdall',
        color: 'Chestnut / Ivory Fleece',
        colorHex: '#3D2314',
        stockQuantity: 0, // Waitlist item
        isActive: true,
        displayPriority: 2,
        productId: 'prod-waitlist-shearling-holdall',
      },
    ],
  },
];

